### ISSUE TITLE
get list of called functions between intervals

### ISSUE THREAD

**Issue by binarykitchen** [tj/node-blocked#4]
when event loop is blocked i would like to see which functions were called during that interval and how many times. especially sync operations. so that i can chase after them ...

probably out of scope or too much for such a small package. but this would help a lot!

**Comment by viztastic** [comment]
+1

**Comment by binarykitchen** [comment]
very old ticket :)

**Comment by viztastic** [comment]
I just ran into this module today and love the idea of it. Would be great if @tj could take this on board... But yes, given you've submitted this over a year ago, not much chance perhaps.

**Comment by robbennet** [comment]
+1

**Comment by naugtur** [comment]
If You're running Node.js 8+ you can get a stacktrace pointing to the blocking function using [blocked-at](https://github.com/naugtur/blocked-at)
